
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // `prisma generate` does not connect to the database, so keep installs
    // working when deployment-only database variables are not injected yet.
    url: process.env.DATABASE_URL ?? "postgresql://localhost:5432/prompts_chat",
  },
});
